[package]
name = "pokemon-icat"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
csv = "1.3.0"
home = "0.5.9"
rand = "0.8.5"
serde = { version = "1.0.210", features = ["derive"] }
viuer = "0.7.1"
